language: python

python:
  - "2.7"  # only 2.7 supported for now

branches:
  only:
  - master  # only build master

# install dependencies
install:
  "make init"

# run tests
script:
  make test

# turn off email notifications
notifications:
  email: false
